"""
Traffic Classification Configuration
"""

# Domains generated by Android OS / Google services.
# These are domain roots, so TrafficFilter can perform safe
# exact/subdomain matching instead of unsafe substring matching.

ANDROID_PATTERNS = [
    "googleapis.com",
    "google.com",
    "gstatic.com",
    "youtube.com",
    "firebaseio.com",
    "connectivitycheck.gstatic.com",
    "android.com",
    "clients.google.com",
    "fonts.googleapis.com",
    "mtalk.google.com",
]

# Third-party services commonly used by applications.
THIRD_PARTY_PATTERNS = [
    "facebook.com",
    "branch.io",
    "adjust.com",
    "appsflyer.com",
    "mixpanel.com",
    "amplitude.com",
    "segment.com",
]
