"""
Traffic Classification Configuration
"""

# Domains generated by Android OS / Google services

ANDROID_PATTERNS = [
    "googleapis",
    "google",
    "gstatic",
    "youtube",
    "doubleclick",
    "firebase",
    "connectivitycheck",
    "android",
    "clients",
    "fonts",
    "mtalk",
]

# Domains belonging to the application

"""
Traffic Classification Configuration
"""

# Domains generated by Android OS / Google services

ANDROID_PATTERNS = [
    "googleapis",
    "google",
    "gstatic",
    "youtube",
    "doubleclick",
    "firebase",
    "connectivitycheck",
    "android",
    "clients",
    "fonts",
    "mtalk",
]


# Third-party services commonly used by apps

THIRD_PARTY_PATTERNS = [
    "facebook",
    "branch",
    "adjust",
    "appsflyer",
    "mixpanel",
    "amplitude",
    "segment",
]

# Third-party services commonly used by apps

THIRD_PARTY_PATTERNS = [
    "facebook",
    "branch",
    "adjust",
    "appsflyer",
    "mixpanel",
    "amplitude",
    "segment",
]